export const LOAD_CONFIG_INITIAL = "LOAD_CONFIG_INITIAL"
export const FILTER_LEADS = "FILTER_LEADS"
export const UPDATE_INFINITE_SCROLL_RESULT = "UPDATE_INFINITE_SCROLL_RESULT"
export const LOAD_SERVICES_INITIAL = "LOAD_SERVICES_INITIAL"