export const LIST_DATA_INITIAL = "LIST_DATA_INITIAL"
export const UPDATE_INFINITE_SCROLL_ACQUISION = "UPDATE_INFINITE_SCROLL_ACQUISION"
export const UPDATE_INFINITE_SCROLL_PAGE = "UPDATE_INFINITE_SCROLL_PAGE"
export const LOADING_DASHBOARD = "LOADING_DASHBOARD"